apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node.fullname" . }}-jwt
  labels:
    {{- include "node.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jwt.secret }}
  jwt.hex: {{ .Values.jwt.secret | b64enc | quote }}
  {{- else }}
  jwt.hex: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
